name: Manual

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "world"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}"
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          touch manual.txt
          git add .
          git commit -m "added file"
          git push
