name: Manual

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "world"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: setup git config
      # run: |
      #   git config user.name "GitHub Actions Bot"
      #   git config user.email "<>"
      - name: send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}"
          touch manual.txt
      - name: push changes
        run: |
          git add manual.txt
          git commit -m "added manual file"
          git push origin
