name: Manual

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "world"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "adoublef"
          git config user.email "kristopherab@gmail.com"
      - name: send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}"
          touch foobar.txt
      - name: push changes
        run: |
          git add manual.txt
          git commit -m "added manual file"
          git push origin
