# Continuous Deployment
name: publish npm package

# On every release created
on:
  push:
    tags: # Sequence of patterns matched against refs/tags
      - "v*" # Matches semantic version

jobs:
  build:
    name: create a release
    runs-on: ubuntu-latest
